Move brg $output before setting from $client
When running brg with -c, the following error would always be displayed:

ERROR: Specify -c or -o, not both.

This was because $output was being set from $client before the check
rather than after. Reordering corrected this.